// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaC-xW70LYlCkI_YdL6GE2qqgoBWRVrJc',
    appId: '1:287326985233:web:7316f675c8013a4ceca5b0',
    messagingSenderId: '287326985233',
    projectId: 'flutterfirenotes-1fccb',
    authDomain: 'flutterfirenotes-1fccb.firebaseapp.com',
    storageBucket: 'flutterfirenotes-1fccb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjKqKMnp_-WcCqWIdErEojmgRgAsXbnCU',
    appId: '1:287326985233:android:ac5cd76518b6e0b1eca5b0',
    messagingSenderId: '287326985233',
    projectId: 'flutterfirenotes-1fccb',
    storageBucket: 'flutterfirenotes-1fccb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoSZN8Zmp7dM3zpePqUwKvKyDMfDn96vc',
    appId: '1:287326985233:ios:45b046c8c60e784feca5b0',
    messagingSenderId: '287326985233',
    projectId: 'flutterfirenotes-1fccb',
    storageBucket: 'flutterfirenotes-1fccb.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoSZN8Zmp7dM3zpePqUwKvKyDMfDn96vc',
    appId: '1:287326985233:ios:99cd7e1052fd6f83eca5b0',
    messagingSenderId: '287326985233',
    projectId: 'flutterfirenotes-1fccb',
    storageBucket: 'flutterfirenotes-1fccb.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
